---
- name: Make sure Fluent Bit (td-agent-bit) is stopped
  service:
    name: td-agent-bit
    state: stopped

- name: Set the currently installed Fluent Bit Version
  command: "{{ _fluent_bit_binary_install_dir }}/td-agent-bit --version | cut -d 'v' -f 2"
  args:
    warn: false
  changed_when: false
  register: __fluent_bit_current_version_output
  check_mode: false
  when: not fluent_bit_version

- name: Set the Fluent Bit Version when not set
  set_fact:
    fluent_bit_version: "{{ __fluent_bit_current_version_output.stdout }}"
  when: not fluent_bit_version

- block:
    - name: Remove Fluent Bit temp files Directory if it exists
      become: false
      file:
        path: "{{ couchbase_fluent_bit_conf_tmp_dir }}"
        state: absent
      delegate_to: localhost
      check_mode: false

    - name: Create Fluent Bit temp files Directory
      become: false
      file:
        path: "{{ couchbase_fluent_bit_conf_tmp_dir }}"
        state: directory
      delegate_to: localhost
      check_mode: false

- block:
    - name: Clone the Couchbase Fluent Bit Repo # noqa 401
      become: false
      git:
        repo: "{{ _couchbase_fluent_bit_repo }}"
        dest: "{{ couchbase_fluent_bit_conf_tmp_dir }}"
        depth: 1
      delegate_to: localhost
      check_mode: false

    - name: Set the Local Fluent Bit Working Directory
      set_fact:
        _couchbase_fluent_bit_workdir: "{{ couchbase_fluent_bit_conf_tmp_dir }}"

  when: couchbase_fluent_bit_source == 'git'

- block:
    - name: Download Couchbase Fluent Bit Conf to local folder
      become: false
      get_url:
        url: "{{ couchbase_fluent_bit_conf_download_url }}"
        dest: "{{ couchbase_fluent_bit_conf_tmp_dir }}/couchbase-fluent-bit-{{ couchbase_fluent_bit_conf_version }}.zip"
        mode: '0644'
      register: _download_conf
      until: _download_conf is succeeded
      retries: 5
      delay: 2
      delegate_to: localhost
      check_mode: false

    - name: Unpack Couchbase Fluent Bit Conf
      become: false
      unarchive:
        src: "{{ couchbase_fluent_bit_conf_tmp_dir }}/couchbase-fluent-bit-{{ couchbase_fluent_bit_conf_version }}.zip"
        dest: "{{ couchbase_fluent_bit_conf_tmp_dir }}"
        creates: "{{ couchbase_fluent_bit_conf_tmp_dir }}/couchbase-fluent-bit-{{ couchbase_fluent_bit_conf_version }}"
      delegate_to: localhost
      check_mode: false

    - name: Set the Local Fluent Bit Working Directory
      set_fact:
        _couchbase_fluent_bit_workdir: "{{ couchbase_fluent_bit_conf_tmp_dir }}/couchbase-fluent-bit-{{ couchbase_fluent_bit_conf_version }}"

  when: couchbase_fluent_bit_source != 'git'

# Copy configuration files to host
- block:
    - name: Copy Configuration Files
      copy:
        src: "{{ _couchbase_fluent_bit_workdir }}/conf/couchbase"
        dest: "{{ fluent_bit_conf_dir }}"
        owner: root
        group: "{{ fluent_bit_user_group }}"
        mode: 0640

    - name: Check if lua directory exists  is installed
      become: false
      stat:
        path: "{{ _couchbase_fluent_bit_workdir }}"
      register: __couchbase_fluent_bit_conf_lua
      delegate_to: localhost
      check_mode: false

    - name: Copy Lua Files if directory exists
      copy:
        src: "{{ _couchbase_fluent_bit_workdir }}/lua"
        dest: "{{ fluent_bit_conf_dir }}"
        owner: root
        group: "{{ fluent_bit_user_group }}"
        mode: 0640
      when: __couchbase_fluent_bit_conf_lua.stat.exists

    - name: Copy Parsers
      copy:
        src: "{{ _couchbase_fluent_bit_workdir }}/conf/parsers-couchbase.conf"
        dest: "{{ fluent_bit_conf_dir }}"
        owner: root
        group: "{{ fluent_bit_user_group }}"
        mode: 0640

    - name: Copy Main Config
      copy:
        src: "{{ _couchbase_fluent_bit_workdir }}/conf/fluent-bit.conf"
        dest: "{{ fluent_bit_conf_dir }}/{{ fluent_bit_conf_file }}"
        owner: root
        group: "{{ fluent_bit_user_group }}"
        mode: 0640

# Update conf files for non-containerized processing
- block:
    - name: Change path references from /fluent-bit/etc to {{ fluent_bit_conf_dir }}
      replace:
        path: "{{ item }}"
        regexp: /fluent-bit/etc/
        replace: "{{ fluent_bit_conf_dir }}/"
      with_items:
        - "{{ fluent_bit_conf_dir }}/{{ fluent_bit_conf_file }}"
        - "{{ fluent_bit_conf_dir }}/couchbase/service.conf"

    - name: Set the HTTP Listen
      lineinfile:
        path: "{{ fluent_bit_conf_dir }}/couchbase/service.conf"
        line: "    HTTP_Listen     {{ fluent_bit_http_listen }}"
        create: yes

    - name: Remove Unnecessary Recording Labels
      lineinfile:
        path: "{{ fluent_bit_conf_dir }}/couchbase/filter-add-common-info.conf"
        state: absent
        regex: "{{ item }}"
      with_items:
        # Remove POD Record Labels
        - Record pod.namespace \$\{POD_NAMESPACE\}
        - Record pod.name \$\{POD_NAME\}
        - Record pod.uid \$\{POD_UID\}
        # Remove Operator Version
        - Record couchbase.operator.version \$\{operator.couchbase.com/version\}
        - Record couchbase.node-config \$\{couchbase_node_conf\}
        - Record couchbase.server.server \$\{couchbase_server\}
        # Remove Services
        - Record couchbase.analytics \$\{couchbase_service_analytics\}
        - Record couchbase.data \$\{couchbase_service_data\}
        - Record couchbase.eventing \$\{couchbase_service_eventing\}
        - Record couchbase.index \$\{couchbase_service_index\}
        - Record couchbase.query \$\{couchbase_service_query\}
        - Record couchbase.search \$\{couchbase_service_search\}
      tags:
        - fluent_bit_remove_labels

    - name: Rename logshipper from "couchbase.sidecar.fluentbit" to "couchbase.fluentbit"
      replace:
        path: "{{ fluent_bit_conf_dir }}/couchbase/filter-add-common-info.conf"
        regexp: "Record logshipper couchbase.sidecar.fluentbit"
        replace: "Record logshipper couchbase.fluentbit"
      tags:
        - fluent_bit_change_shipper

    - name: Change Cluster Name from couchbase_cluster to couchbase_cluster_name for consistency
      replace:
        path: "{{ fluent_bit_conf_dir }}/couchbase/filter-add-common-info.conf"
        regexp: "{{ item }}"
        replace: "Record couchbase.cluster_name ${couchbase_cluster_name}"
      with_items:
        - Record couchbase.cluster \$\{couchbase_cluster\}

    - name: Change server version env var reference to a standardized reference
      replace:
        path: "{{ fluent_bit_conf_dir }}/couchbase/filter-add-common-info.conf"
        regexp: "Record couchbase.server.version \\$\\{server.couchbase.com/version\\}"
        replace: "Record couchbase.server.version ${couchbase_server_version}"

    - name: Fix LUA Path
      replace:
        path: "{{ fluent_bit_conf_dir }}/service.conf"
        regexp: "/fluent-bit/etc/common.lua"
        replace: "{{ fluent_bit_conf_dir }}/lua/common.lua"

    - name: Allow log level to be determined via Environment Variable
      replace:
        path: "{{ fluent_bit_conf_dir }}/couchbase/filter-add-common-info.conf"
        regexp: "log_level\\s+\\w"
        replace: "log_level       ${FLUENT_BIT_LOG_LEVEL}"

    - name: Update the log-level filter to ensure __temp_level_fixed is defaulted
      blockinfile:
        path: "{{ fluent_bit_conf_dir }}/couchbase/filter-handle-levels.conf"
        insertbefore: "# Handle logs without levels directly"
        block: |
          # Default the __temp_level_fixed variable to N
          [FILTER]
              Name        modify
              Match       couchbase.log.*
              Alias       default_temp_level_fixed
              Set         __temp_level_fixed                              N
      tags:
        - fluent_bit_update_log_level

# - name: Uncomment filter-common-problems
#   replace:
#     path: "{{ fluent_bit_conf_dir }}/{{ fluent_bit_conf_file}}"
#     regexp: "# @include {{ fluent_bit_conf_dir }}/couchbase/filter-common-problems.conf"
#     replace: "@include {{ fluent_bit_conf_dir }}/couchbase/filter-common-problems.conf"
#   tags:
#     - fluent_bit_configure
#     - fluent_bit_include_common_problems

# Handle Output
- include: output.yml

- block:
    - name: Add Streams so logs can be reprocessed
      template:
        src: conf/streams-couchbase.conf.j2
        dest: "{{ fluent_bit_conf_dir }}/streams-couchbase.conf"
        owner: root
        group: "{{ fluent_bit_user_group }}"
        mode: 0640
      tags:
        - fluent_bit_streams
        - fluent_bit_add_stream

    - name: Add Filter file for streams
      template:
        src: conf/couchbase/filter-handle-streams.conf.j2
        dest: "{{ fluent_bit_conf_dir }}/couchbase/filter-handle-streams.conf"
        owner: root
        group: "{{ fluent_bit_user_group }}"
        mode: 0640
      tags:
        - fluent_bit_streams
        - fluent_bit_streams_level_in_tag

    - name: Add streams_file to service.conf
      lineinfile:
        path: "{{ fluent_bit_conf_dir }}/couchbase/service.conf"
        line: "{{ item }}"
        create: true
      with_items:
        - "    streams_file    {{ fluent_bit_conf_dir }}/streams-couchbase.conf"
      tags:
        - fluent_bit_streams

    - name: "Include streams filter in {{ fluent_bit_conf_file }}"
      lineinfile:
        path: "{{ fluent_bit_conf_dir }}/{{ fluent_bit_conf_file }}"
        line: "{{ item }}"
        create: true
        insertafter: "@include {{ fluent_bit_conf_dir }}/couchbase/filter-handle-filenames.conf"
      with_items:
        - "@include {{ fluent_bit_conf_dir }}/couchbase/filter-handle-streams.conf"
      tags:
        - fluent_bit_streams

- name: Cleanup Downloaded Files
  become: false
  file:
    path: "{{ couchbase_fluent_bit_conf_tmp_dir }}"
    state: absent
  delegate_to: localhost
  check_mode: false
  tags:
    - fluent_bit_configure
