---
- name: Create Fluent Bit couchbase/input Directory
  file:
    path: "{{ fluent_bit_conf_dir }}/couchbase/input"
    state: directory
    owner: root
    group: "{{ fluent_bit_user_group }}"
    mode: 0755

# For simplicity several inputs can manage multiple log files, so not be repeated.  However, to manage
# it is easier to have a separate conf file for each log file monitored and they can be dynamically
# included through globbing i.e. conf/couchbase/input/in-*.conf
- name: Include Single File Inputs
  template:
    src: "conf/couchbase/input/in-{{ item | regex_replace('\\.log$', '-log') }}.conf.j2"
    dest: "{{ fluent_bit_conf_dir }}/couchbase/input/in-{{ item | regex_replace('\\.log$', '-log') }}.conf"
    owner: root
    group: "{{ fluent_bit_user_group }}"
    mode: 0640
  when: item in couchbase_logs
  with_items:
    - audit.log
    - http.log
    - analytics.log
    - memcached.log
    - prometheus.log
    - xdcr.log
    - rebalance-report

- name: Include Eventing and FTS File Inputs
  template:
    src: "conf/couchbase/input/in-eventing-fts-log.conf.j2"
    dest: "{{ fluent_bit_conf_dir }}/couchbase/input/in-{{ item | regex_replace('\\.log$', '-log') }}.conf"
    owner: root
    group: "{{ fluent_bit_user_group }}"
    mode: 0640
  when: item in couchbase_logs
  with_items:
    - eventing.log
    - fts.log

- name: Include Erlang Log Files
  template:
    src: "conf/couchbase/input/in-erlang-multiline-log.conf.j2"
    dest: "{{ fluent_bit_conf_dir }}/couchbase/input/in-{{ item | regex_replace('\\.log$', '-log') }}.conf"
    owner: root
    group: "{{ fluent_bit_user_group }}"
    mode: 0640
  when: item in couchbase_logs
  with_items:
    - babysitter.log
    - couchdb.log
    - debug.log
    - json_rpc.log
    - mapreduce_errors.log
    - metakv.log
    - ns_couchdb.log
    - reports.log
