---
- name: Create Fluent Bit couchbase/input Directory
  ansible.builtin.file:
    path: "{{ fluent_bit_conf_dir }}/couchbase/input"
    state: directory
    owner: "{{ fluent_bit_user }}"
    group: "{{ fluent_bit_user_group }}"
    mode: 0775

# Configure Input Logs
- include_tasks:
    file: input/logs.yml
    apply:
      become: true

# Configure Slow Query Input
- include_tasks:
    file: input/slow-query.yml
    apply:
      become: true

# Configure Kernel Input
- include_tasks:
    file: input/kernel.yml
    apply:
      become: true
