---
- name: Install Fluent Bit agent dependencies (postgresql-libs lua)
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - postgresql-libs
    - lua

- name: Add user group "{{ fluent_bit_user_group }}"
  group:
    name: "{{ fluent_bit_user_group }}"
    system: true
    state: present

- name: Add user "{{ fluent_bit_user }}"
  user:
    name: "{{ fluent_bit_user }}"
    comment: "Fluent Bit Account"
    groups:
      - "{{ fluent_bit_user_group }}"
      - "{{ fluent_bit_couchbase_user_group }}"
    system: true
    shell: "{{ fluent_bit_user_shell }}"
    createhome: "{{ fluent_bit_user_createhome }}"
  when: fluent_bit_user != 'root'

- name: Package Install
  block:
    - name: Include the OS specific repository
      include_tasks: "{{ item }}"
      with_first_found:
        - "repos/{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "repos/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "repos/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "repos/{{ ansible_distribution | lower }}.yml"
        - "repos/{{ ansible_os_family | lower }}.yml"

    - name: Install the latest version of Fluent Bit
      package:
        name: fluent-bit
        state: latest    # # noqa package-latest

  when: not __fluent_bit_local_install and __fluent_bit_do_install

- name: Propagate local fluent-bit binary
  ansible.builtin.copy:
    src: "{{ fluent_bit_local_binary_path }}"
    dest: "{{ fluent_bit_local_binary_path }}/fluent-bit"
    mode: 0755
    owner: root
    group: "{{ fluent_bit_user_group }}"
  when: __fluent_bit_local_install

- name: Ensure fluent-bit permissions are correctly set
  become: true
  file:
    path: "{{ fluent_bit_conf_dir }}"
    state: directory
    owner: root
    group: "{{ fluent_bit_user_group }}"
    mode: 0755
  with_items:
    - "{{ fluent_bit_conf_dir }}"
    - "{{ _fluent_bit_binary_install_dir }}"

- name: Remove storage buffer directory exists
  file:
    path: "{{ fluent_bit_storage_buffer_path }}"
    state: absent

- name: Ensure storage buffer directory exists
  file:
    path: "{{ fluent_bit_storage_buffer_path }}"
    state: directory
    owner: "{{ fluent_bit_user }}"
    group: "{{ fluent_bit_user_group }}"
    mode: 0755
