---
- include_tasks:
    file: preflight.yml
    apply:
      become: true
      tags:
        - fluent_bit_install
        - fluent_bit_configure
        - fluent_bit_run
  tags:
    - fluent_bit_install
    - fluent_bit_configure
    - fluent_bit_run

- include_tasks:
    file: install.yml
    apply:
      become: true
      tags:
        - fluent_bit_install
  tags:
    - fluent_bit_install
  when: __fluent_bit_do_install

- include_tasks:
    file: configure.yml
    apply:
      become: true
      tags:
        - fluent_bit_configure
  tags:
    - fluent_bit_configure

- name: Ensure Fluent Bit is Started and Enabled on Boot
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    name: fluent-bit
    enabled: true
    state: started
  tags:
    - fluent_bit_install
    - fluent_bit_configure
    - fluent_bit_run
