---
- name: Create Fluent Bit couchbase/output Directory
  ansible.builtin.file:
    path: "{{ fluent_bit_conf_dir }}/couchbase/output"
    state: directory
    owner: "{{ fluent_bit_user }}"
    group: "{{ fluent_bit_user_group }}"
    mode: 0775

# Configure stdout
- include_tasks:
    file: output/stdout.yml
    apply:
      become: true

# Configure cbhealthagent
- include_tasks:
    file: output/cbhealthagent.yml
    apply:
      become: true

# Configure loki
- include_tasks:
    file: output/loki.yml
    apply:
      become: true

# Configure splunk
- include_tasks:
    file: output/splunk.yml
    apply:
      become: true

# Configure elasticsearch
- include_tasks:
    file: output/elasticsearch.yml
    apply:
      become: true
