---
- name: Create Fluent Bit couchbase/output Directory
  file:
    path: "{{ fluent_bit_conf_dir }}/couchbase/output"
    state: directory
    owner: root
    group: "{{ fluent_bit_user_group }}"
    mode: 0755

- name: Configure Standard Out
  template:
    src: "conf/couchbase/output/out-stdout.conf.j2"
    dest: "{{ fluent_bit_conf_dir }}/couchbase/output/out-stdout.conf"
    owner: root
    group: "{{ fluent_bit_user_group }}"
    mode: 0640

- name: Configure cbhealthagent
  block:
    - name: Add cbhealthagent to conf
      lineinfile:
        path: "{{ fluent_bit_conf_dir }}/{{ fluent_bit_conf_file }}"
        state: present
        line: "@include {{ fluent_bit_conf_dir }}/couchbase/output/out-cbhealthagent.conf"

    - name: Include cbhealthagent Output conf
      template:
        src: "conf/couchbase/output/out-cbhealthagent.conf.j2"
        dest: "{{ fluent_bit_conf_dir }}/couchbase/output/out-cbhealthagent.conf"
        owner: root
        group: "{{ fluent_bit_user_group }}"
        mode: 0640

  when: fluent_bit_cbhealthagent_enabled

- name: Configure Loki
  block:
    - name: Add Loki to conf
      lineinfile:
        path: "{{ fluent_bit_conf_dir }}/{{ fluent_bit_conf_file }}"
        state: present
        line: "@include {{ fluent_bit_conf_dir }}/couchbase/output/out-loki.conf"

    - name: Include Loki Output conf
      template:
        src: "conf/couchbase/output/out-loki.conf.j2"
        dest: "{{ fluent_bit_conf_dir }}/couchbase/output/out-loki.conf"
        owner: root
        group: "{{ fluent_bit_user_group }}"
        mode: 0640

  when: fluent_bit_loki_enabled

- name: Configure Splunk
  block:
    - name: Add Splunk to conf
      lineinfile:
        path: "{{ fluent_bit_conf_dir }}/{{ fluent_bit_conf_file }}"
        state: present
        line: "@include {{ fluent_bit_conf_dir }}/couchbase/output/out-splunk.conf"

    - name: Include Splunk Output conf
      template:
        src: "conf/couchbase/output/out-splunk.conf.j2"
        dest: "{{ fluent_bit_conf_dir }}/couchbase/output/out-splunk.conf"
        owner: root
        group: "{{ fluent_bit_user_group }}"
        mode: 0640

  when: fluent_bit_splunk_enabled

- name: Configure Elasticsearch
  block:
    - name: Add Elasticsearch to conf
      lineinfile:
        path: "{{ fluent_bit_conf_dir }}/{{ fluent_bit_conf_file }}"
        state: present
        line: "@include {{ fluent_bit_conf_dir }}/couchbase/output/out-elastic.conf"

    - name: Include Elasticsearch Output conf
      template:
        src: "conf/couchbase/output/out-elastic.conf.j2"
        dest: "{{ fluent_bit_conf_dir }}/couchbase/output/out-elastic.conf"
        owner: root
        group: "{{ fluent_bit_user_group }}"
        mode: 0640

  when: fluent_bit_es_enabled
